apiVersion: v1
kind: Service
metadata:
  name: hpa-demo
  labels:
    app: hpa-demo
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: hpa-demo
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-demo
spec:
  selector:
    matchLabels:
      app: hpa-demo
  template:
    metadata:
      labels:
        app: hpa-demo
    spec:
      containers:
      - name: hpa-demo
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
          name: "http"
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "48Mi"
            cpu: "400m"